name: slimy_card_plus
description: It provides a beautiful slime-like animation of a Card that separates into two.
version: 1.0.7
homepage: https://github.com/zhangyc/SlimyCard-Animated-Flutter-Package.git

environment:
   sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
   - assets/flare/
